/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PayRouteImport } from './routes/pay'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardTerminalsRouteImport } from './routes/dashboard.terminals'
import { Route as DashboardSystemRouteImport } from './routes/dashboard.system'
import { Route as DashboardReportsRouteImport } from './routes/dashboard.reports'
import { Route as DashboardLogsRouteImport } from './routes/dashboard.logs'
import { Route as DashboardLiveRouteImport } from './routes/dashboard.live'
import { Route as DashboardCustomersRouteImport } from './routes/dashboard.customers'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as DashboardAlertsRouteImport } from './routes/dashboard.alerts'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTerminalsRoute = DashboardTerminalsRouteImport.update({
  id: '/terminals',
  path: '/terminals',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSystemRoute = DashboardSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLogsRoute = DashboardLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLiveRoute = DashboardLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCustomersRoute = DashboardCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAlertsRoute = DashboardAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/pay': typeof PayRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/live': typeof DashboardLiveRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/system': typeof DashboardSystemRoute
  '/dashboard/terminals': typeof DashboardTerminalsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pay': typeof PayRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/live': typeof DashboardLiveRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/system': typeof DashboardSystemRoute
  '/dashboard/terminals': typeof DashboardTerminalsRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/pay': typeof PayRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/live': typeof DashboardLiveRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/system': typeof DashboardSystemRoute
  '/dashboard/terminals': typeof DashboardTerminalsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/pay'
    | '/profile'
    | '/register'
    | '/dashboard/alerts'
    | '/dashboard/analytics'
    | '/dashboard/customers'
    | '/dashboard/live'
    | '/dashboard/logs'
    | '/dashboard/reports'
    | '/dashboard/system'
    | '/dashboard/terminals'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pay'
    | '/profile'
    | '/register'
    | '/dashboard/alerts'
    | '/dashboard/analytics'
    | '/dashboard/customers'
    | '/dashboard/live'
    | '/dashboard/logs'
    | '/dashboard/reports'
    | '/dashboard/system'
    | '/dashboard/terminals'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/pay'
    | '/profile'
    | '/register'
    | '/dashboard/alerts'
    | '/dashboard/analytics'
    | '/dashboard/customers'
    | '/dashboard/live'
    | '/dashboard/logs'
    | '/dashboard/reports'
    | '/dashboard/system'
    | '/dashboard/terminals'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  PayRoute: typeof PayRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/terminals': {
      id: '/dashboard/terminals'
      path: '/terminals'
      fullPath: '/dashboard/terminals'
      preLoaderRoute: typeof DashboardTerminalsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/system': {
      id: '/dashboard/system'
      path: '/system'
      fullPath: '/dashboard/system'
      preLoaderRoute: typeof DashboardSystemRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/logs': {
      id: '/dashboard/logs'
      path: '/logs'
      fullPath: '/dashboard/logs'
      preLoaderRoute: typeof DashboardLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/live': {
      id: '/dashboard/live'
      path: '/live'
      fullPath: '/dashboard/live'
      preLoaderRoute: typeof DashboardLiveRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/customers': {
      id: '/dashboard/customers'
      path: '/customers'
      fullPath: '/dashboard/customers'
      preLoaderRoute: typeof DashboardCustomersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/alerts': {
      id: '/dashboard/alerts'
      path: '/alerts'
      fullPath: '/dashboard/alerts'
      preLoaderRoute: typeof DashboardAlertsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAlertsRoute: typeof DashboardAlertsRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardCustomersRoute: typeof DashboardCustomersRoute
  DashboardLiveRoute: typeof DashboardLiveRoute
  DashboardLogsRoute: typeof DashboardLogsRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardSystemRoute: typeof DashboardSystemRoute
  DashboardTerminalsRoute: typeof DashboardTerminalsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAlertsRoute: DashboardAlertsRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardCustomersRoute: DashboardCustomersRoute,
  DashboardLiveRoute: DashboardLiveRoute,
  DashboardLogsRoute: DashboardLogsRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardSystemRoute: DashboardSystemRoute,
  DashboardTerminalsRoute: DashboardTerminalsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  PayRoute: PayRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
